trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      name: envFile
      inputs:
        secureFile: '.env'
    - task: CopyFiles@2
      inputs:
        contents: ${envFile.secureFilePath}
        targetFolder: $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Build & Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: DockerHub
        repository: leherv/discord_release_notifier
        tags: |
          $(tag)
